//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateDataForTesting.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.MobileService")]
    public interface MobileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:MobileService/Login", ReplyAction="urn:MobileService/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:MobileService/UpdateStreetStatus", ReplyAction="urn:MobileService/UpdateStreetStatusResponse")]
        bool UpdateStreetStatus(string username, string country, string city, string district, string street, double latitude, double longitude, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:MobileService/GetStreetStatus", ReplyAction="urn:MobileService/GetStreetStatusResponse")]
        string[] GetStreetStatus(string country, string city, string district, string street, double latitude, double longitude, string mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:MobileService/GenerateData", ReplyAction="urn:MobileService/GenerateDataResponse")]
        void GenerateData();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:MobileService/GetNearbyTrafficJam", ReplyAction="urn:MobileService/GetNearbyTrafficJamResponse")]
        string[] GetNearbyTrafficJam(double latitude, double longitude, string city, string district, string street);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MobileServiceChannel : GenerateDataForTesting.ServiceReference1.MobileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobileServiceClient : System.ServiceModel.ClientBase<GenerateDataForTesting.ServiceReference1.MobileService>, GenerateDataForTesting.ServiceReference1.MobileService {
        
        public MobileServiceClient() {
        }
        
        public MobileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public bool UpdateStreetStatus(string username, string country, string city, string district, string street, double latitude, double longitude, string status) {
            return base.Channel.UpdateStreetStatus(username, country, city, district, street, latitude, longitude, status);
        }
        
        public string[] GetStreetStatus(string country, string city, string district, string street, double latitude, double longitude, string mode) {
            return base.Channel.GetStreetStatus(country, city, district, street, latitude, longitude, mode);
        }
        
        public void GenerateData() {
            base.Channel.GenerateData();
        }
        
        public string[] GetNearbyTrafficJam(double latitude, double longitude, string city, string district, string street) {
            return base.Channel.GetNearbyTrafficJam(latitude, longitude, city, district, street);
        }
    }
}
